package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Xpdcompanyrelationship generated by hbm2java
 */
@Entity
@Table
public class XpdCompanyRelationship implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private SysCurrency sysCurrencyId;
	
	@ManyToOne
	private SysPaymentMode sysPaymentModeId;
	
	@ManyToOne
	private XpdCompany xpdcompanyByXpdBuyerCompanyId;
	
	@ManyToOne
	private XpdCompany xpdcompanyByXpdSupplierCompanyId;
	
	@Column
	private String description;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;
	@Column
	private String supplierBankAccountNo;
	@Column
	private String supplierBankAddress;
	@Column
	private String supplierBankIfsc;
	@Column
	private String supplierBankUpi;
	@Column
	private String supplierCustomerAlso;
	@Column
	private boolean isBlacklisted;
	@ManyToOne
	private RefLookupValue refLooupValue;

	public RefLookupValue getRefLooupValueId() {
		return refLooupValue;
	}

	public void setRefLooupValueId(RefLookupValue refLooupValue) {
		this.refLooupValue = refLooupValue;
	}

	public XpdCompanyRelationship(long id) {
		super();
		this.id = id;
	}
	
	public XpdCompanyRelationship() {
		
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public SysCurrency getSysCurrencyId() {
		return sysCurrencyId;
	}

	public void setSysCurrencyId(SysCurrency sysCurrencyId) {
		this.sysCurrencyId = sysCurrencyId;
	}

	public SysPaymentMode getSysPaymentModeId() {
		return sysPaymentModeId;
	}

	public void setSysPaymentModeId(SysPaymentMode sysPaymentModeId) {
		this.sysPaymentModeId = sysPaymentModeId;
	}

	public XpdCompany getXpdcompanyByXpdBuyerCompanyId() {
		return this.xpdcompanyByXpdBuyerCompanyId;
	}

	public void setXpdcompanyByXpdBuyerCompanyId(XpdCompany xpdcompanyByXpdBuyerCompanyId) {
		this.xpdcompanyByXpdBuyerCompanyId = xpdcompanyByXpdBuyerCompanyId;
	}

	public XpdCompany getXpdcompanyByXpdSupplierCompanyId() {
		return this.xpdcompanyByXpdSupplierCompanyId;
	}

	public void setXpdcompanyByXpdSupplierCompanyId(XpdCompany xpdcompanyByXpdSupplierCompanyId) {
		this.xpdcompanyByXpdSupplierCompanyId = xpdcompanyByXpdSupplierCompanyId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getSupplierBankAccountNo() {
		return this.supplierBankAccountNo;
	}

	public void setSupplierBankAccountNo(String supplierBankAccountNo) {
		this.supplierBankAccountNo = supplierBankAccountNo;
	}

	public String getSupplierBankAddress() {
		return this.supplierBankAddress;
	}

	public void setSupplierBankAddress(String supplierBankAddress) {
		this.supplierBankAddress = supplierBankAddress;
	}

	public String getSupplierBankIfsc() {
		return this.supplierBankIfsc;
	}

	public void setSupplierBankIfsc(String supplierBankIfsc) {
		this.supplierBankIfsc = supplierBankIfsc;
	}

	public String getSupplierBankUpi() {
		return this.supplierBankUpi;
	}

	public void setSupplierBankUpi(String supplierBankUpi) {
		this.supplierBankUpi = supplierBankUpi;
	}

	public String getSupplierCustomerAlso() {
		return supplierCustomerAlso;
	}

	public void setSupplierCustomerAlso(String supplierCustomerAlso) {
		this.supplierCustomerAlso = supplierCustomerAlso;
	}

	public boolean getIsBlacklisted() {
		return isBlacklisted;
	}

	public void setIsBlacklisted(boolean isBlacklisted) {
		this.isBlacklisted = isBlacklisted;
	}

}
