package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.springframework.context.annotation.Lazy;

/**
 * Xpdcompany generated by hbm2java
 */
@Entity
@Table
public class XpdCompany implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private SysCompanyCategory syscompanycategory;
	
	@ManyToOne
	private SysIndustry sysindustry;
	
	@Column
	private String companyName;
	@Column
	private String description;
	@Column
	private String syncToken;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;
	@Column
	private String legalName;
	@Column
	private String email;
	@Column
	private String landline;
	@Column
	private String mobile;
	@Column
	private String fax;
	@Column
	private String website;
	@Column
	private String pan;
	@Column
	private String tan;
	@Column
	private String cin;
	@Column
	private String iec;
	@Column
	private String logo;
	@Column
	private Long priority;
	@Column
	private String stockTicker;
	@Column
	private String linkedinPage;
	@Column
	private String twitterPage;
	@Column
	private String facebookPage;
	@Column
	private Boolean isBuyer;
	@Column
	private String vendorId;
	@Column
	private String gstin;
	@Column
	private boolean isDeleted;
	@Column
	private String defaultPercentage;
	
	@OneToMany (fetch=FetchType.EAGER)
	@JoinColumn(name = "xpd_company_id_id")
	private Set<XpdOrgMaster> orgMasters = new HashSet<XpdOrgMaster>();
	
//	@OneToMany
//	@JoinColumn(name = "xpd_company_id_id")
//	private Set<XpdOffer> xpdOffers = new HashSet<XpdOffer>();
	
	
	public XpdCompany (long id, String name, Set<XpdOrgMaster> orgMasters) {
		this.id = id;
		this.companyName = name;
		this.orgMasters = orgMasters;
	}
	
	public XpdCompany() {
		
	}
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public SysCompanyCategory getSyscompanycategory() {
		return syscompanycategory;
	}
	public void setSyscompanycategory(SysCompanyCategory syscompanycategory) {
		this.syscompanycategory = syscompanycategory;
	}
	public SysIndustry getSysindustry() {
		return sysindustry;
	}
	public void setSysindustry(SysIndustry sysindustry) {
		this.sysindustry = sysindustry;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getSyncToken() {
		return syncToken;
	}
	public void setSyncToken(String syncToken) {
		this.syncToken = syncToken;
	}
	public long getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public long getModifiedBy() {
		return modifiedBy;
	}
	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getModifiedDate() {
		return modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public String getLegalName() {
		return legalName;
	}
	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getLandline() {
		return landline;
	}
	public void setLandline(String landline) {
		this.landline = landline;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getFax() {
		return fax;
	}
	public void setFax(String fax) {
		this.fax = fax;
	}
	public String getWebsite() {
		return website;
	}
	public void setWebsite(String website) {
		this.website = website;
	}
	public String getPan() {
		return pan;
	}
	public void setPan(String pan) {
		this.pan = pan;
	}
	public String getTan() {
		return tan;
	}
	public void setTan(String tan) {
		this.tan = tan;
	}
	public String getCin() {
		return cin;
	}
	public void setCin(String cin) {
		this.cin = cin;
	}
	public String getIec() {
		return iec;
	}
	public void setIec(String iec) {
		this.iec = iec;
	}
	public String getLogo() {
		return logo;
	}
	public void setLogo(String logo) {
		this.logo = logo;
	}
	public Long getPriority() {
		return priority;
	}
	public void setPriority(Long priority) {
		this.priority = priority;
	}
	public String getStockTicker() {
		return stockTicker;
	}
	public void setStockTicker(String stockTicker) {
		this.stockTicker = stockTicker;
	}
	public String getLinkedinPage() {
		return linkedinPage;
	}
	public void setLinkedinPage(String linkedinPage) {
		this.linkedinPage = linkedinPage;
	}
	public String getTwitterPage() {
		return twitterPage;
	}
	public void setTwitterPage(String twitterPage) {
		this.twitterPage = twitterPage;
	}
	public String getFacebookPage() {
		return facebookPage;
	}
	public void setFacebookPage(String facebookPage) {
		this.facebookPage = facebookPage;
	}
	public Boolean getIsBuyer() {
		return isBuyer;
	}
	public void setIsBuyer(Boolean isBuyer) {
		this.isBuyer = isBuyer;
	}
	public Set<XpdOrgMaster> getOrgMasters() {
		return orgMasters;
	}
	public void setOrgMasters(Set<XpdOrgMaster> orgMasters) {
		this.orgMasters = orgMasters;
	}
	public String getVendorId() {
		return vendorId;
	}
	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}
	public String getGstin() {
		return gstin;
	}
	public void setGstin(String gstin) {
		this.gstin = gstin;
	}
	public boolean isDeleted() {
		return isDeleted;
	}
	public void setDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getDefaultPercentage() {
		return defaultPercentage;
	}

	public void setDefaultPercentage(String defaultPercentage) {
		this.defaultPercentage = defaultPercentage;
	}
	
}
