package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Xpdinvoiceoffer generated by hbm2java
 */
@Entity
@Table
public class XpdInvoiceOffer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;
	
	@ManyToOne
	private XpdOrgMaster xpdOrgMasterId;
	
	@ManyToOne
	private XpdInvoice xpdInvoiceId;
	
	@ManyToOne
	private XpdOffer xpdOfferId;
	
	@Column
	private Boolean isActive;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;
	
	@Column
	private double annualPercentage;
	
	@Column
	private double discountAmount;
	@Column
	private double daysRemaining;
	@Column
	private double discountPercent30Days;
	@Column
	private double appliedDiscount;
	@Column
	private double netAmount;
	@Column
	private Date newDueDate;
	
	@Column
	private double dueAmount;

	public XpdInvoiceOffer() {
		
	}
	
	public XpdInvoiceOffer(long id, double netAmount, double dueAmount, double discountAmount, Date newDueDate) {
		this.id = id;
		this.netAmount = netAmount;
		this.dueAmount = dueAmount;
		this.discountAmount = discountAmount;
		this.newDueDate = newDueDate;
	}
	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public XpdCompany getXpdCompanyId() {
		return xpdCompanyId;
	}

	public void setXpdCompanyId(XpdCompany xpdCompanyId) {
		this.xpdCompanyId = xpdCompanyId;
	}

	public XpdInvoice getXpdInvoiceId() {
		return xpdInvoiceId;
	}

	public void setXpdInvoiceId(XpdInvoice xpdInvoiceId) {
		this.xpdInvoiceId = xpdInvoiceId;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public XpdOffer getXpdOfferId() {
		return xpdOfferId;
	}

	public void setXpdOfferId(XpdOffer xpdOfferId) {
		this.xpdOfferId = xpdOfferId;
	}

	public double getAnnualPercentage() {
		return annualPercentage;
	}

	public void setAnnualPercentage(double annualPercentage) {
		this.annualPercentage = annualPercentage;
	}

	public double getDiscountAmount() {
		return discountAmount;
	}

	public void setDiscountAmount(double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public double getDaysRemaining() {
		return daysRemaining;
	}

	public void setDaysRemaining(double daysRemaining) {
		this.daysRemaining = daysRemaining;
	}

	public double getDiscountPercent30Days() {
		return discountPercent30Days;
	}

	public void setDiscountPercent30Days(double discountPercent30Days) {
		this.discountPercent30Days = discountPercent30Days;
	}

	public double getAppliedDiscount() {
		return appliedDiscount;
	}

	public void setAppliedDiscount(double appliedDiscount) {
		this.appliedDiscount = appliedDiscount;
	}

	public double getNetAmount() {
		return netAmount;
	}

	public void setNetAmount(double netAmount) {
		this.netAmount = netAmount;
	}

	public Date getNewDueDate() {
		return newDueDate;
	}

	public void setNewDueDate(Date newDueDate) {
		this.newDueDate = newDueDate;
	}

	public double getDueAmount() {
		return dueAmount;
	}

	public void setDueAmount(double dueAmount) {
		this.dueAmount = dueAmount;
	}

	public XpdOrgMaster getXpdOrgMasterId() {
		return xpdOrgMasterId;
	}

	public void setXpdOrgMasterId(XpdOrgMaster xpdOrgMasterId) {
		this.xpdOrgMasterId = xpdOrgMasterId;
	}

}
