package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Xpdinvoicenoteitem generated by hbm2java
 */
@Entity
@Table
public class XpdInvoiceNoteItem implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;
	
	@ManyToOne
	private XpdInvoiceNote xpdInvoiceNoteId;
	
	@Column
	private String itemType;
	@Column
	private String itemDescription;
	@Column
	private BigDecimal itemQuantity;
	@Column
	private String measurementUnit;
	@Column
	private Double itemRate;
	@Column
	private BigDecimal cgstRate;
	@Column
	private Double cgstAmount;
	@Column
	private BigDecimal igstRate;
	@Column
	private Double igstAmount;
	@Column
	private BigDecimal cessRate;
	@Column
	private Double cessAmount;
	@Column
	private Double itemTaxableValue;
	@Column
	private Double discountAmount;
	@Column
	private Boolean isNonTaxable;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public XpdCompany getXpdCompanyId() {
		return xpdCompanyId;
	}

	public void setXpdCompanyId(XpdCompany xpdCompanyId) {
		this.xpdCompanyId = xpdCompanyId;
	}

	public XpdInvoiceNote getXpdInvoiceNoteId() {
		return xpdInvoiceNoteId;
	}

	public void setXpdInvoiceNoteId(XpdInvoiceNote xpdInvoiceNoteId) {
		this.xpdInvoiceNoteId = xpdInvoiceNoteId;
	}

	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public BigDecimal getItemQuantity() {
		return this.itemQuantity;
	}

	public void setItemQuantity(BigDecimal itemQuantity) {
		this.itemQuantity = itemQuantity;
	}

	public String getMeasurementUnit() {
		return this.measurementUnit;
	}

	public void setMeasurementUnit(String measurementUnit) {
		this.measurementUnit = measurementUnit;
	}

	public Double getItemRate() {
		return this.itemRate;
	}

	public void setItemRate(Double itemRate) {
		this.itemRate = itemRate;
	}

	public BigDecimal getCgstRate() {
		return this.cgstRate;
	}

	public void setCgstRate(BigDecimal cgstRate) {
		this.cgstRate = cgstRate;
	}

	public Double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(Double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	public BigDecimal getIgstRate() {
		return this.igstRate;
	}

	public void setIgstRate(BigDecimal igstRate) {
		this.igstRate = igstRate;
	}

	public Double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(Double igstAmount) {
		this.igstAmount = igstAmount;
	}

	public BigDecimal getCessRate() {
		return this.cessRate;
	}

	public void setCessRate(BigDecimal cessRate) {
		this.cessRate = cessRate;
	}

	public Double getCessAmount() {
		return this.cessAmount;
	}

	public void setCessAmount(Double cessAmount) {
		this.cessAmount = cessAmount;
	}

	public Double getItemTaxableValue() {
		return this.itemTaxableValue;
	}

	public void setItemTaxableValue(Double itemTaxableValue) {
		this.itemTaxableValue = itemTaxableValue;
	}

	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public Boolean getIsNonTaxable() {
		return this.isNonTaxable;
	}

	public void setIsNonTaxable(Boolean isNonTaxable) {
		this.isNonTaxable = isNonTaxable;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
