package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Xpdinvoicenote generated by hbm2java
 */
@Entity
@Table
public class XpdInvoiceNote implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;
	
	@ManyToOne
	private XpdInvoice xpdInvoiceId;
	
	@ManyToOne
	private XpdInvoiceNoteType noteType;
	
	@Column
	private String noteNumber;
	@Column
	private Date noteDate;
	@Column
	private String noteReason;
	@Column
	private Boolean isReverseCharge;
	@Column
	private Date originalNoteDate;
	@Column
	private String originalNoteNumber;
	@Column
	private Boolean isActive;
	@Column
	private Boolean isTdsDeducted;
	@Column
	private Double balance;
	@Column
	private String paymentStatus;
	@Column
	private Double discountAmount;
	@Column
	private Double totalTrasactionValue;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;
	@Column
	private long invoicenotetypeid;
	@Column
	private String vendorId;
	@Column
	private Date clearingDate;
	@Column
	private String clearingDoc;
	@Column
	private String buyerDocumentNumber;
	
	private String financialYear;
	private String baselineDate;
	private String currency;
	private String postingKey;
	private String glAccount;
	private String paymentTerm;
	private String glAccount2;
	private String costCenter;
	private String documentType;
	
	@ManyToOne
	private XpdOrgMaster xpdOrgMasterId;
	
	
	public String getBuyerDocumentNumber() {
		return buyerDocumentNumber;
	}

	public void setBuyerDocumentNumber(String buyerDocumentNumber) {
		this.buyerDocumentNumber = buyerDocumentNumber;
	}

	public String getFinancialYear() {
		return financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}

	public String getBaselineDate() {
		return baselineDate;
	}

	public void setBaselineDate(String baselineDate) {
		this.baselineDate = baselineDate;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPostingKey() {
		return postingKey;
	}

	public void setPostingKey(String postingKey) {
		this.postingKey = postingKey;
	}

	public String getGlAccount() {
		return glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	public String getPaymentTerm() {
		return paymentTerm;
	}

	public void setPaymentTerm(String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}

	public String getGlAccount2() {
		return glAccount2;
	}

	public void setGlAccount2(String glAccount2) {
		this.glAccount2 = glAccount2;
	}

	public String getCostCenter() {
		return costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	public String getDocumentType() {
		return documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public XpdOrgMaster getXpdOrgMasterId() {
		return xpdOrgMasterId;
	}

	public void setXpdOrgMasterId(XpdOrgMaster xpdOrgMasterId) {
		this.xpdOrgMasterId = xpdOrgMasterId;
	}


	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public XpdCompany getXpdCompanyId() {
		return xpdCompanyId;
	}

	public void setXpdCompanyId(XpdCompany xpdCompanyId) {
		this.xpdCompanyId = xpdCompanyId;
	}

	public XpdInvoice getXpdInvoiceId() {
		return xpdInvoiceId;
	}

	public void setXpdInvoiceId(XpdInvoice xpdInvoiceId) {
		this.xpdInvoiceId = xpdInvoiceId;
	}

	public String getNoteNumber() {
		return this.noteNumber;
	}

	public void setNoteNumber(String noteNumber) {
		this.noteNumber = noteNumber;
	}

	public Date getNoteDate() {
		return this.noteDate;
	}

	public void setNoteDate(Date noteDate) {
		this.noteDate = noteDate;
	}

	public String getNoteReason() {
		return this.noteReason;
	}

	public void setNoteReason(String noteReason) {
		this.noteReason = noteReason;
	}

	public Boolean getIsReverseCharge() {
		return this.isReverseCharge;
	}

	public void setIsReverseCharge(Boolean isReverseCharge) {
		this.isReverseCharge = isReverseCharge;
	}

	public Date getOriginalNoteDate() {
		return this.originalNoteDate;
	}

	public void setOriginalNoteDate(Date originalNoteDate) {
		this.originalNoteDate = originalNoteDate;
	}

	public String getOriginalNoteNumber() {
		return this.originalNoteNumber;
	}

	public void setOriginalNoteNumber(String originalNoteNumber) {
		this.originalNoteNumber = originalNoteNumber;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Boolean getIsTdsDeducted() {
		return this.isTdsDeducted;
	}

	public void setIsTdsDeducted(Boolean isTdsDeducted) {
		this.isTdsDeducted = isTdsDeducted;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public Double getTotalTrasactionValue() {
		return this.totalTrasactionValue;
	}

	public void setTotalTrasactionValue(Double totalTrasactionValue) {
		this.totalTrasactionValue = totalTrasactionValue;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public long getInvoicenotetypeid() {
		return this.invoicenotetypeid;
	}

	public void setInvoicenotetypeid(long invoicenotetypeid) {
		this.invoicenotetypeid = invoicenotetypeid;
	}

	public String getVendorId() {
		return vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	public Date getClearingDate() {
		return clearingDate;
	}

	public void setClearingDate(Date clearingDate) {
		this.clearingDate = clearingDate;
	}

	public String getClearingDoc() {
		return clearingDoc;
	}

	public void setClearingDoc(String clearingDoc) {
		this.clearingDoc = clearingDoc;
	}

	public XpdInvoiceNoteType getNoteType() {
		return noteType;
	}

	public void setNoteType(XpdInvoiceNoteType noteType) {
		this.noteType = noteType;
	}

}
