package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xpdinvoice generated by hbm2java
 */
@Entity
@Table
public class XpdInvoicePaymentTerms implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@Column
	private String termsOfPayment;
	@Column
	private String ownExplanation;
	@Column
	private String dayLimit;
	@Column
	private String dateType;
	@Column
	private String fixedDay;
	@Column
	private String additionalMonths;
	@Column
	private String noOfDays1;
	@Column
	private String percentage1;
	@Column
	private String noOfDays2;
	@Column
	private String percentage2;
	@Column
	private String noOfDays3;
	@Column
	private String fixedDate1;
	@Column
	private String additionalMonthsTerm1;
	@Column
	private String fixedDate2;
	@Column
	private String additionalMonthsTerm2;
	@Column
	private String fixedDate3;
	@Column
	private String additionalMonthsTerm3;
	@Column
	private String printTermsOfPaymentInRvPapers;
	@Column
	private String blockKey;
	@Column
	private String transfPaymentBlockForChanges;
	@Column
	private String standardText;
	@Column
	private String paymentMethod;
	@Column
	private String transfPymtMethodForChange;
	@Column
	private String accountType;
	@Column
	private String installmentPayment;
	@Column
	private String recEntriesSupplementFmMaster;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public String getTermsOfPayment() {
		return termsOfPayment;
	}

	public void setTermsOfPayment(String termsOfPayment) {
		this.termsOfPayment = termsOfPayment;
	}

	public String getOwnExplanation() {
		return ownExplanation;
	}

	public void setOwnExplanation(String ownExplanation) {
		this.ownExplanation = ownExplanation;
	}

	public String getDayLimit() {
		return dayLimit;
	}

	public void setDayLimit(String dayLimit) {
		this.dayLimit = dayLimit;
	}

	public String getDateType() {
		return dateType;
	}

	public void setDateType(String dateType) {
		this.dateType = dateType;
	}

	public String getFixedDay() {
		return fixedDay;
	}

	public void setFixedDay(String fixedDay) {
		this.fixedDay = fixedDay;
	}

	public String getAdditionalMonths() {
		return additionalMonths;
	}

	public void setAdditionalMonths(String additionalMonths) {
		this.additionalMonths = additionalMonths;
	}

	public String getNoOfDays1() {
		return noOfDays1;
	}

	public void setNoOfDays1(String noOfDays1) {
		this.noOfDays1 = noOfDays1;
	}

	public String getPercentage1() {
		return percentage1;
	}

	public void setPercentage1(String percentage1) {
		this.percentage1 = percentage1;
	}

	public String getNoOfDays2() {
		return noOfDays2;
	}

	public void setNoOfDays2(String noOfDays2) {
		this.noOfDays2 = noOfDays2;
	}

	public String getPercentage2() {
		return percentage2;
	}

	public void setPercentage2(String percentage2) {
		this.percentage2 = percentage2;
	}

	public String getNoOfDays3() {
		return noOfDays3;
	}

	public void setNoOfDays3(String noOfDays3) {
		this.noOfDays3 = noOfDays3;
	}

	public String getFixedDate1() {
		return fixedDate1;
	}

	public void setFixedDate1(String fixedDate1) {
		this.fixedDate1 = fixedDate1;
	}

	public String getAdditionalMonthsTerm1() {
		return additionalMonthsTerm1;
	}

	public void setAdditionalMonthsTerm1(String additionalMonthsTerm1) {
		this.additionalMonthsTerm1 = additionalMonthsTerm1;
	}

	public String getFixedDate2() {
		return fixedDate2;
	}

	public void setFixedDate2(String fixedDate2) {
		this.fixedDate2 = fixedDate2;
	}

	public String getAdditionalMonthsTerm2() {
		return additionalMonthsTerm2;
	}

	public void setAdditionalMonthsTerm2(String additionalMonthsTerm2) {
		this.additionalMonthsTerm2 = additionalMonthsTerm2;
	}

	public String getFixedDate3() {
		return fixedDate3;
	}

	public void setFixedDate3(String fixedDate3) {
		this.fixedDate3 = fixedDate3;
	}

	public String getAdditionalMonthsTerm3() {
		return additionalMonthsTerm3;
	}

	public void setAdditionalMonthsTerm3(String additionalMonthsTerm3) {
		this.additionalMonthsTerm3 = additionalMonthsTerm3;
	}

	public String getPrintTermsOfPaymentInRvPapers() {
		return printTermsOfPaymentInRvPapers;
	}

	public void setPrintTermsOfPaymentInRvPapers(String printTermsOfPaymentInRvPapers) {
		this.printTermsOfPaymentInRvPapers = printTermsOfPaymentInRvPapers;
	}

	public String getBlockKey() {
		return blockKey;
	}

	public void setBlockKey(String blockKey) {
		this.blockKey = blockKey;
	}

	public String getTransfPaymentBlockForChanges() {
		return transfPaymentBlockForChanges;
	}

	public void setTransfPaymentBlockForChanges(String transfPaymentBlockForChanges) {
		this.transfPaymentBlockForChanges = transfPaymentBlockForChanges;
	}

	public String getStandardText() {
		return standardText;
	}

	public void setStandardText(String standardText) {
		this.standardText = standardText;
	}

	public String getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public String getTransfPymtMethodForChange() {
		return transfPymtMethodForChange;
	}

	public void setTransfPymtMethodForChange(String transfPymtMethodForChange) {
		this.transfPymtMethodForChange = transfPymtMethodForChange;
	}

	public String getAccountType() {
		return accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getInstallmentPayment() {
		return installmentPayment;
	}

	public void setInstallmentPayment(String installmentPayment) {
		this.installmentPayment = installmentPayment;
	}

	public String getRecEntriesSupplementFmMaster() {
		return recEntriesSupplementFmMaster;
	}

	public void setRecEntriesSupplementFmMaster(String recEntriesSupplementFmMaster) {
		this.recEntriesSupplementFmMaster = recEntriesSupplementFmMaster;
	}



		
}
