package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xpdinvoice generated by hbm2java
 */
@Entity
@Table
public class XpdInvoice implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	@Column
	private String invoiceNumber;
	@Column
	private Date invoiceDate;
	@Column
	private String stateOfSupply;
	@Column
	private String invoiceType;
	@Column
	private String gstStatus;
	@Column
	private Boolean isUinRegistered;
	@Column
	private Date returnFilingDate;
	@Column
	private Boolean isReverseCharge;
	@Column
	private Date originalInvoiceDate;
	@Column
	private String originalInvoicenumeric;
	@Column
	private String originalCustomerBillingGstin;
	@Column
	private Boolean isActive;
	@Column
	private String ecomMarketPlaceGstin;
	@Column
	private Boolean isBillOfSupply;
	@Column
	private Boolean isTdsDeducted;
	@Column
	private String documentType;
	@Column
	private Double balance;
	@Column
	private String paymentStatus;
	@Column
	private Double discountAmount;
	@Column
	private Double totalTrasactionValue;
	@Column
	private long createdBy;
	@Column
	private Date createdDate;
	@Column
	private long modifiedBy;
	@Column
	private Date modifiedDate;
	@Column
	private Date dueDate;
	@Column
	private Date newDueDate;
	@Column
	private String vendorId;
	@Column
	private String buyerDocumentNumber;
	@Column
	private String financialYear;
	@Column
	private Date baselineDate;
	@Column
	private String currency;
	@Column
	private String postingKey;
	@Column
	private String glAccount;
	@Column
	private String paymentTerm;
	@Column
	private Date clearingDate;
	@Column
	private String clearingDoc;
	@Column
	private String glAccount2;
	
	public String getGlAccount2() {
		return glAccount2;
	}

	public void setGlAccount2(String glAccount2) {
		this.glAccount2 = glAccount2;
	}

	public String getCostCenter() {
		return costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	private String costCenter;
	
	@ManyToOne
	private XpdOrgMaster xpdOrgMasterId;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;
//	
//	@ManyToOne
//	private XpdOrgMasterSupplierRelationship orgMasterSupplierRelationshipId;
//	
//	@OneToMany
//	private Set<XpdInvoiceOffer> xpdInvoiceOffersId; 
//	
//	@OneToMany
//	private Set<XpdInvoiceStatus> xpdInvoiceStatusId; 

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getStateOfSupply() {
		return this.stateOfSupply;
	}

	public void setStateOfSupply(String stateOfSupply) {
		this.stateOfSupply = stateOfSupply;
	}

	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	public String getGstStatus() {
		return this.gstStatus;
	}

	public void setGstStatus(String gstStatus) {
		this.gstStatus = gstStatus;
	}

	public Boolean getIsUinRegistered() {
		return this.isUinRegistered;
	}

	public void setIsUinRegistered(Boolean isUinRegistered) {
		this.isUinRegistered = isUinRegistered;
	}

	public Date getReturnFilingDate() {
		return this.returnFilingDate;
	}

	public void setReturnFilingDate(Date returnFilingDate) {
		this.returnFilingDate = returnFilingDate;
	}

	public Boolean getIsReverseCharge() {
		return this.isReverseCharge;
	}

	public void setIsReverseCharge(Boolean isReverseCharge) {
		this.isReverseCharge = isReverseCharge;
	}

	public Date getOriginalInvoiceDate() {
		return this.originalInvoiceDate;
	}

	public void setOriginalInvoiceDate(Date originalInvoiceDate) {
		this.originalInvoiceDate = originalInvoiceDate;
	}

	public String getOriginalInvoicenumeric() {
		return this.originalInvoicenumeric;
	}

	public void setOriginalInvoicenumeric(String originalInvoicenumeric) {
		this.originalInvoicenumeric = originalInvoicenumeric;
	}

	public String getOriginalCustomerBillingGstin() {
		return this.originalCustomerBillingGstin;
	}

	public void setOriginalCustomerBillingGstin(String originalCustomerBillingGstin) {
		this.originalCustomerBillingGstin = originalCustomerBillingGstin;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getEcomMarketPlaceGstin() {
		return this.ecomMarketPlaceGstin;
	}

	public void setEcomMarketPlaceGstin(String ecomMarketPlaceGstin) {
		this.ecomMarketPlaceGstin = ecomMarketPlaceGstin;
	}

	public Boolean getIsBillOfSupply() {
		return this.isBillOfSupply;
	}

	public void setIsBillOfSupply(Boolean isBillOfSupply) {
		this.isBillOfSupply = isBillOfSupply;
	}

	public Boolean getIsTdsDeducted() {
		return this.isTdsDeducted;
	}

	public void setIsTdsDeducted(Boolean isTdsDeducted) {
		this.isTdsDeducted = isTdsDeducted;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public Double getTotalTrasactionValue() {
		return this.totalTrasactionValue;
	}

	public void setTotalTrasactionValue(Double totalTrasactionValue) {
		this.totalTrasactionValue = totalTrasactionValue;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Date getNewDueDate() {
		return newDueDate;
	}

	public void setNewDueDate(Date newDueDate) {
		this.newDueDate = newDueDate;
	}

	public String getVendorId() {
		return vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	public String getBuyerDocumentNumber() {
		return buyerDocumentNumber;
	}

	public void setBuyerDocumentNumber(String buyerDocumentNumber) {
		this.buyerDocumentNumber = buyerDocumentNumber;
	}

	public String getFinancialYear() {
		return financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}

	public Date getBaselineDate() {
		return baselineDate;
	}

	public void setBaselineDate(Date baselineDate) {
		this.baselineDate = baselineDate;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPostingKey() {
		return postingKey;
	}

	public void setPostingKey(String postingKey) {
		this.postingKey = postingKey;
	}

	public String getGlAccount() {
		return glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	public String getPaymentTerm() {
		return paymentTerm;
	}

	public void setPaymentTerm(String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}

	public Date getClearingDate() {
		return clearingDate;
	}

	public void setClearingDate(Date clearingDate) {
		this.clearingDate = clearingDate;
	}

	public String getClearingDoc() {
		return clearingDoc;
	}

	public void setClearingDoc(String clearingDoc) {
		this.clearingDoc = clearingDoc;
	}

	public XpdOrgMaster getXpdOrgMasterId() {
		return xpdOrgMasterId;
	}

	public void setXpdOrgMasterId(XpdOrgMaster xpdOrgMasterId) {
		this.xpdOrgMasterId = xpdOrgMasterId;
	}

	public XpdCompany getXpdCompanyId() {
		return xpdCompanyId;
	}

	public void setXpdCompanyId(XpdCompany xpdCompanyId) {
		this.xpdCompanyId = xpdCompanyId;
	}
}
