package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xpdoffer generated by hbm2java
 */
@Entity
@Table
public class XpdOffer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@ManyToOne
	private SysOfferType sysOfferTypeId;
	
	@OneToMany(mappedBy="xpdOffer")
	private List<XpdOfferCriteria> offerCriterias; 
	
	private String offerName;
	private String description;
	private Date startDate;
	private Date endDate;
	private BigDecimal processingDays;
	private BigDecimal annualPercentage;
	private BigDecimal minPercentage;
	private BigDecimal maxPercentage;
	private BigDecimal targetAveragePercentage;
	private Double auctionTargetAmmount;
	private long createdBy;
	private Date createdDate;
	private long modifiedBy;
	private Date modifiedDate;
	private Double netAmount;

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public SysOfferType getSysOfferTypeId() {
		return sysOfferTypeId;
	}

	public void setSysOfferTypeId(SysOfferType sysOfferTypeId) {
		this.sysOfferTypeId = sysOfferTypeId;
	}

	public String getOfferName() {
		return this.offerName;
	}

	public void setOfferName(String offerName) {
		this.offerName = offerName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getProcessingDays() {
		return this.processingDays;
	}

	public void setProcessingDays(BigDecimal processingDays) {
		this.processingDays = processingDays;
	}

	public BigDecimal getAnnualPercentage() {
		return this.annualPercentage;
	}

	public void setAnnualPercentage(BigDecimal annualPercentage) {
		this.annualPercentage = annualPercentage;
	}

	public BigDecimal getMinPercentage() {
		return this.minPercentage;
	}

	public void setMinPercentage(BigDecimal minPercentage) {
		this.minPercentage = minPercentage;
	}

	public BigDecimal getMaxPercentage() {
		return this.maxPercentage;
	}

	public void setMaxPercentage(BigDecimal maxPercentage) {
		this.maxPercentage = maxPercentage;
	}

	public BigDecimal getTargetAveragePercentage() {
		return this.targetAveragePercentage;
	}

	public void setTargetAveragePercentage(BigDecimal targetAveragePercentage) {
		this.targetAveragePercentage = targetAveragePercentage;
	}

	public Double getAuctionTargetAmmount() {
		return this.auctionTargetAmmount;
	}

	public void setAuctionTargetAmmount(Double auctionTargetAmmount) {
		this.auctionTargetAmmount = auctionTargetAmmount;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Double getNetAmount() {
		return netAmount;
	}

	public void setNetAmount(Double netAmount) {
		this.netAmount = netAmount;
	}

	public List<XpdOfferCriteria> getOfferCriterias() {
		return offerCriterias;
	}

	public void setOfferCriterias(List<XpdOfferCriteria> offerCriterias) {
		this.offerCriterias = offerCriterias;
	}
}
