package org.xpd.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * XpdPaymentDateStrategy generated by hbm2java
 */
@Entity
@Table
public class XpdPaymentDateStrategy implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
		
	private String workingDays;
	
	private String paymentDateStrategy;
	
	private Integer minimumDaysGap;
	
	private String particularDayOfWeek;
	
	private boolean isActive;
	
	@ManyToOne
	private XpdUser createdBy;

	private Date createdDate;
	
	@ManyToOne
	private XpdUser modifiedBy;
	
	private Date modifiedDate;
	
	@ManyToOne
	private XpdCompany company;
	
	public XpdPaymentDateStrategy() {
		
	}
	
	public XpdPaymentDateStrategy(Long id, String workingDays, String paymentDateStrategy, Integer minimumDaysGap,
			String particularDayOfWeek) {
		super();
		this.id = id;
		this.workingDays = workingDays;
		this.paymentDateStrategy = paymentDateStrategy;
		this.minimumDaysGap = minimumDaysGap;
		this.particularDayOfWeek = particularDayOfWeek;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getWorkingDays() {
		return workingDays;
	}

	public void setWorkingDays(String workingDays) {
		this.workingDays = workingDays;
	}

	public String getPaymentDateStrategy() {
		return paymentDateStrategy;
	}

	public void setPaymentDateStrategy(String paymentDateStrategy) {
		this.paymentDateStrategy = paymentDateStrategy;
	}

	public Integer getMinimumDaysGap() {
		return minimumDaysGap;
	}

	public void setMinimumDaysGap(Integer minimumDaysGap) {
		this.minimumDaysGap = minimumDaysGap;
	}

	public String getParticularDayOfWeek() {
		return particularDayOfWeek;
	}

	public void setParticularDayOfWeek(String particularDayOfWeek) {
		this.particularDayOfWeek = particularDayOfWeek;
	}

	public XpdCompany getCompany() {
		return company;
	}

	public void setCompany(XpdCompany company) {
		this.company = company;
	}

	public XpdUser getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(XpdUser createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public XpdUser getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(XpdUser modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}
	
}
