package org.xpd.models;
// Generated 20 Aug, 2018 7:46:07 PM by Hibernate Tools 5.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Xpdinvoice generated by hbm2java
 */
@Entity
@Table
public class XpdPayments implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	@Column
	private double balance;
	@Column
	private double discountAmount;
	@Column
	private long invoieTypeId;
	@Column
	private boolean isActive;
	@Column
	private boolean isReverseCharge;
	@Column
	private boolean isTdsDeducted;
	@Column
	private Date noteDate;
	@Column
	private String noteNumber;
	@Column
	private String noteReason;
	@Column
	private String noteType;
	@Column
	private Date originalNoteDate;
	@Column
	private String originalNoteNumber;
	@Column
	private String paymentStatus;
	@Column
	private double totalTransactionValue;
	@Column
	private String vendorId;
	@Column
	private Date clearingDate;
	@Column
	private String clearingDoc;
	
	@ManyToOne
	private XpdUser createdby;
	@Column
	private String createddate;
	
	@ManyToOne
	private XpdUser modifiedby;
	
	private String modifieddate;
	
	@Column
	private boolean isUpdated;
	
	@ManyToOne
	private XpdCompany xpdCompanyId;
	
	@ManyToOne
	private XpdInvoice xpdInvoiceId;
	
	@ManyToOne
	private XpdOrgMaster xpdOrgMasterId;
	@Column
	private String buyerDocumentNumber;
	@Column
	private String financialYear;
	@Column
	private String baselineDate;
	@Column
	private String currency;
	@Column
	private String postingKey;
	@Column
	private String glAccount;
	@Column
	private String paymentTerm;
	@Column
	private String glAccount2;
	@Column
	private String costCenter;
	@Column
	private String documentType;
	
	public XpdOrgMaster getXpdOrgMasterId() {
		return xpdOrgMasterId;
	}

	public void setXpdOrgMasterId(XpdOrgMaster xpdOrgMasterId) {
		this.xpdOrgMasterId = xpdOrgMasterId;
	}

	public String getBuyerDocumentNumber() {
		return buyerDocumentNumber;
	}

	public void setBuyerDocumentNumber(String buyerDocumentNumber) {
		this.buyerDocumentNumber = buyerDocumentNumber;
	}

	public String getFinancialYear() {
		return financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}

	public String getBaselineDate() {
		return baselineDate;
	}

	public void setBaselineDate(String baselineDate) {
		this.baselineDate = baselineDate;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPostingKey() {
		return postingKey;
	}

	public void setPostingKey(String postingKey) {
		this.postingKey = postingKey;
	}

	public String getGlAccount() {
		return glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	public String getPaymentTerm() {
		return paymentTerm;
	}

	public void setPaymentTerm(String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}

	public String getGlAccount2() {
		return glAccount2;
	}

	public void setGlAccount2(String glAccount2) {
		this.glAccount2 = glAccount2;
	}

	public String getCostCenter() {
		return costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	public String getDocumentType() {
		return documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public void setUpdated(boolean isUpdated) {
		this.isUpdated = isUpdated;
	}


	
	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public double getDiscountAmount() {
		return discountAmount;
	}

	public void setDiscountAmount(double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public long getInvoieTypeId() {
		return invoieTypeId;
	}

	public void setInvoieTypeId(long invoieTypeId) {
		this.invoieTypeId = invoieTypeId;
	}

	public boolean isActive() {
		return isActive;
	}

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	public boolean isReverseCharge() {
		return isReverseCharge;
	}

	public void setReverseCharge(boolean isReverseCharge) {
		this.isReverseCharge = isReverseCharge;
	}

	public boolean isTdsDeducted() {
		return isTdsDeducted;
	}

	public void setTdsDeducted(boolean isTdsDeducted) {
		this.isTdsDeducted = isTdsDeducted;
	}

	public Date getNoteDate() {
		return noteDate;
	}

	public void setNoteDate(Date noteDate) {
		this.noteDate = noteDate;
	}

	public String getNoteNumber() {
		return noteNumber;
	}

	public void setNoteNumber(String noteNumber) {
		this.noteNumber = noteNumber;
	}

	public String getNoteReason() {
		return noteReason;
	}

	public void setNoteReason(String noteReason) {
		this.noteReason = noteReason;
	}

	public String getNoteType() {
		return noteType;
	}

	public void setNoteType(String noteType) {
		this.noteType = noteType;
	}

	public Date getOriginalNoteDate() {
		return originalNoteDate;
	}

	public void setOriginalNoteDate(Date originalNoteDate) {
		this.originalNoteDate = originalNoteDate;
	}

	public String getOriginalNoteNumber() {
		return originalNoteNumber;
	}

	public void setOriginalNoteNumber(String originalNoteNumber) {
		this.originalNoteNumber = originalNoteNumber;
	}

	public String getPaymentStatus() {
		return paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public double getTotalTransactionValue() {
		return totalTransactionValue;
	}

	public void setTotalTransactionValue(double totalTransactionValue) {
		this.totalTransactionValue = totalTransactionValue;
	}

	public String getVendorId() {
		return vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	public Date getClearingDate() {
		return clearingDate;
	}

	public void setClearingDate(Date clearingDate) {
		this.clearingDate = clearingDate;
	}

	public String getClearingDoc() {
		return clearingDoc;
	}

	public void setClearingDoc(String clearingDoc) {
		this.clearingDoc = clearingDoc;
	}

	public XpdUser getCreatedby() {
		return createdby;
	}

	public void setCreatedby(XpdUser createdby) {
		this.createdby = createdby;
	}

	public String getCreateddate() {
		return createddate;
	}

	public void setCreateddate(String createddate) {
		this.createddate = createddate;
	}

	public XpdUser getModifiedby() {
		return modifiedby;
	}

	public void setModifiedby(XpdUser modifiedby) {
		this.modifiedby = modifiedby;
	}

	public String getModifieddate() {
		return modifieddate;
	}

	public void setModifieddate(String modifieddate) {
		this.modifieddate = modifieddate;
	}

	public XpdCompany getXpdCompanyId() {
		return xpdCompanyId;
	}

	public void setXpdCompanyId(XpdCompany xpdCompanyId) {
		this.xpdCompanyId = xpdCompanyId;
	}

	public XpdInvoice getXpdInvoiceId() {
		return xpdInvoiceId;
	}

	public void setXpdInvoiceId(XpdInvoice xpdInvoiceId) {
		this.xpdInvoiceId = xpdInvoiceId;
	}

	public boolean getIsUpdated() {
		return isUpdated;
	}

	public void setIsUpdated(boolean isUpdated) {
		this.isUpdated = isUpdated;
	}
}
