package org.xpd.util;
import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
  

public class Md5_Encryt {

   public static String getMd5(String input) 
	    { 
	        try { 
	  
	            // Static getInstance method is called with hashing MD5 
	            MessageDigest md = MessageDigest.getInstance("MD5"); 
	  
	            // digest() method is called to calculate message digest 
	            //  of an input digest() return array of byte 
	            byte[] messageDigest = md.digest(input.getBytes()); 
	  
	            // Convert byte array into signum representation 
	            BigInteger no = new BigInteger(1, messageDigest); 
	  
	            // Convert message digest into hex value 
	            String hashtext = no.toString(16); 
	            while (hashtext.length() < 32) { 
	                hashtext = "0" + hashtext; 
	            } 
	            return hashtext; 
	        }  
	  
	        // For specifying wrong message digest algorithms 
	        catch (NoSuchAlgorithmException e) { 
	            throw new RuntimeException(e); 
	        } 
	    } 
	  
	    // Driver code 
	    public static void main(String args[]) throws NoSuchAlgorithmException 
	    { 
	        String s = "Good";
	        String first=getMd5(s);
	        System.out.println("Your HashCode Generated by MD5 is: " +first);
	        
	        String s2 = "good";
	        String second=getMd5(s2);
	        System.out.println("Your HashCode Generated by MD5 is: " +second);
	        
	        if(s.equals(s2)) {
	        	System.out.println("Both the Hascodes are Equal");
	        } else {
	        	System.out.println("Both the Hascodes are not Equal");
	        }
	    } 
}

